// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// AccountsAttributes accounts attributes
// swagger:model accountsAttributes
type AccountsAttributes struct {

	// awsaccount id
	AwsaccountID string `json:"awsaccount-id,omitempty"`

	// billing account id
	BillingAccountID string `json:"billing-account-id,omitempty"`

	// cost package
	CostPackage bool `json:"cost-package,omitempty"`

	// created date
	CreatedDate int64 `json:"created-date,omitempty"`

	// environment
	Environment string `json:"environment,omitempty"`

	// last checked date
	LastCheckedDate int64 `json:"last-checked-date,omitempty"`

	// last monitoring event date
	LastMonitoringEventDate int64 `json:"last-monitoring-event-date,omitempty"`

	// last notified date
	LastNotifiedDate int64 `json:"last-notified-date,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// security package
	SecurityPackage bool `json:"security-package,omitempty"`
}

// Validate validates this accounts attributes
func (m *AccountsAttributes) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AccountsAttributes) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AccountsAttributes) UnmarshalBinary(b []byte) error {
	var res AccountsAttributes
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
