// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// AccountAttributesAccess account attributes access
// swagger:model accountAttributesAccess
type AccountAttributesAccess struct {

	// keys
	Keys *AccountAttributesAccessKeys `json:"keys,omitempty"`
}

// Validate validates this account attributes access
func (m *AccountAttributesAccess) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateKeys(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AccountAttributesAccess) validateKeys(formats strfmt.Registry) error {

	if swag.IsZero(m.Keys) { // not required
		return nil
	}

	if m.Keys != nil {
		if err := m.Keys.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("keys")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *AccountAttributesAccess) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AccountAttributesAccess) UnmarshalBinary(b []byte) error {
	var res AccountAttributesAccess
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
