// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// ErrorErrorsItemsSourceSource error errors items source source
// swagger:model errorErrorsItemsSourceSource
type ErrorErrorsItemsSourceSource struct {

	// pointer
	Pointer string `json:"pointer,omitempty"`
}

// Validate validates this error errors items source source
func (m *ErrorErrorsItemsSourceSource) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ErrorErrorsItemsSourceSource) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ErrorErrorsItemsSourceSource) UnmarshalBinary(b []byte) error {
	var res ErrorErrorsItemsSourceSource
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
