// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// GetExternalIDOKBodyDataAttributes get external Id o k body data attributes
// swagger:model getExternalIdOKBodyDataAttributes
type GetExternalIDOKBodyDataAttributes struct {

	// valid until
	ValidUntil int64 `json:"valid-until,omitempty"`
}

// Validate validates this get external Id o k body data attributes
func (m *GetExternalIDOKBodyDataAttributes) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GetExternalIDOKBodyDataAttributes) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetExternalIDOKBodyDataAttributes) UnmarshalBinary(b []byte) error {
	var res GetExternalIDOKBodyDataAttributes
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
