// Code generated by go-swagger; DO NOT EDIT.

package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/erikvanbrakel/terraform-provider-cloudconformity/go-cloudconformity/models"
)

// CreateAccountReader is a Reader for the CreateAccount structure.
type CreateAccountReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateAccountReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewCreateAccountOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewCreateAccountBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewCreateAccountUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewCreateAccountForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewCreateAccountNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 422:
		result := NewCreateAccountUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewCreateAccountInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateAccountOK creates a CreateAccountOK with default headers values
func NewCreateAccountOK() *CreateAccountOK {
	return &CreateAccountOK{}
}

/*CreateAccountOK handles this case with default header values.

OK
*/
type CreateAccountOK struct {
	Payload *models.CreateAccountOKBody
}

func (o *CreateAccountOK) Error() string {
	return fmt.Sprintf("[POST /accounts][%d] createAccountOK  %+v", 200, o.Payload)
}

func (o *CreateAccountOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CreateAccountOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateAccountBadRequest creates a CreateAccountBadRequest with default headers values
func NewCreateAccountBadRequest() *CreateAccountBadRequest {
	return &CreateAccountBadRequest{}
}

/*CreateAccountBadRequest handles this case with default header values.

Bad Request
*/
type CreateAccountBadRequest struct {
	Payload *models.Error
}

func (o *CreateAccountBadRequest) Error() string {
	return fmt.Sprintf("[POST /accounts][%d] createAccountBadRequest  %+v", 400, o.Payload)
}

func (o *CreateAccountBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateAccountUnauthorized creates a CreateAccountUnauthorized with default headers values
func NewCreateAccountUnauthorized() *CreateAccountUnauthorized {
	return &CreateAccountUnauthorized{}
}

/*CreateAccountUnauthorized handles this case with default header values.

Unauthorized
*/
type CreateAccountUnauthorized struct {
	Payload *models.Error
}

func (o *CreateAccountUnauthorized) Error() string {
	return fmt.Sprintf("[POST /accounts][%d] createAccountUnauthorized  %+v", 401, o.Payload)
}

func (o *CreateAccountUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateAccountForbidden creates a CreateAccountForbidden with default headers values
func NewCreateAccountForbidden() *CreateAccountForbidden {
	return &CreateAccountForbidden{}
}

/*CreateAccountForbidden handles this case with default header values.

Forbidden
*/
type CreateAccountForbidden struct {
	Payload *models.Error
}

func (o *CreateAccountForbidden) Error() string {
	return fmt.Sprintf("[POST /accounts][%d] createAccountForbidden  %+v", 403, o.Payload)
}

func (o *CreateAccountForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateAccountNotFound creates a CreateAccountNotFound with default headers values
func NewCreateAccountNotFound() *CreateAccountNotFound {
	return &CreateAccountNotFound{}
}

/*CreateAccountNotFound handles this case with default header values.

Not Found
*/
type CreateAccountNotFound struct {
	Payload *models.Error
}

func (o *CreateAccountNotFound) Error() string {
	return fmt.Sprintf("[POST /accounts][%d] createAccountNotFound  %+v", 404, o.Payload)
}

func (o *CreateAccountNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateAccountUnprocessableEntity creates a CreateAccountUnprocessableEntity with default headers values
func NewCreateAccountUnprocessableEntity() *CreateAccountUnprocessableEntity {
	return &CreateAccountUnprocessableEntity{}
}

/*CreateAccountUnprocessableEntity handles this case with default header values.

Unprocessable Entity
*/
type CreateAccountUnprocessableEntity struct {
	Payload *models.Error
}

func (o *CreateAccountUnprocessableEntity) Error() string {
	return fmt.Sprintf("[POST /accounts][%d] createAccountUnprocessableEntity  %+v", 422, o.Payload)
}

func (o *CreateAccountUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateAccountInternalServerError creates a CreateAccountInternalServerError with default headers values
func NewCreateAccountInternalServerError() *CreateAccountInternalServerError {
	return &CreateAccountInternalServerError{}
}

/*CreateAccountInternalServerError handles this case with default header values.

Internal Server Error
*/
type CreateAccountInternalServerError struct {
	Payload *models.Error
}

func (o *CreateAccountInternalServerError) Error() string {
	return fmt.Sprintf("[POST /accounts][%d] createAccountInternalServerError  %+v", 500, o.Payload)
}

func (o *CreateAccountInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
