// Code generated by go-swagger; DO NOT EDIT.

package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewScanAccountParams creates a new ScanAccountParams object
// with the default values initialized.
func NewScanAccountParams() *ScanAccountParams {
	var ()
	return &ScanAccountParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewScanAccountParamsWithTimeout creates a new ScanAccountParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewScanAccountParamsWithTimeout(timeout time.Duration) *ScanAccountParams {
	var ()
	return &ScanAccountParams{

		timeout: timeout,
	}
}

// NewScanAccountParamsWithContext creates a new ScanAccountParams object
// with the default values initialized, and the ability to set a context for a request
func NewScanAccountParamsWithContext(ctx context.Context) *ScanAccountParams {
	var ()
	return &ScanAccountParams{

		Context: ctx,
	}
}

// NewScanAccountParamsWithHTTPClient creates a new ScanAccountParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewScanAccountParamsWithHTTPClient(client *http.Client) *ScanAccountParams {
	var ()
	return &ScanAccountParams{
		HTTPClient: client,
	}
}

/*ScanAccountParams contains all the parameters to send to the API endpoint
for the scan account operation typically these are written to a http.Request
*/
type ScanAccountParams struct {

	/*AccountID
	  Account ID

	*/
	AccountID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the scan account params
func (o *ScanAccountParams) WithTimeout(timeout time.Duration) *ScanAccountParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the scan account params
func (o *ScanAccountParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the scan account params
func (o *ScanAccountParams) WithContext(ctx context.Context) *ScanAccountParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the scan account params
func (o *ScanAccountParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the scan account params
func (o *ScanAccountParams) WithHTTPClient(client *http.Client) *ScanAccountParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the scan account params
func (o *ScanAccountParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAccountID adds the accountID to the scan account params
func (o *ScanAccountParams) WithAccountID(accountID string) *ScanAccountParams {
	o.SetAccountID(accountID)
	return o
}

// SetAccountID adds the accountId to the scan account params
func (o *ScanAccountParams) SetAccountID(accountID string) {
	o.AccountID = accountID
}

// WriteToRequest writes these params to a swagger request
func (o *ScanAccountParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param accountId
	if err := r.SetPathParam("accountId", o.AccountID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
