// Code generated by go-swagger; DO NOT EDIT.

package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// ScanAccountReader is a Reader for the ScanAccount structure.
type ScanAccountReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ScanAccountReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewScanAccountOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewScanAccountOK creates a ScanAccountOK with default headers values
func NewScanAccountOK() *ScanAccountOK {
	return &ScanAccountOK{}
}

/*ScanAccountOK handles this case with default header values.

OK
*/
type ScanAccountOK struct {
}

func (o *ScanAccountOK) Error() string {
	return fmt.Sprintf("[POST /accounts/{accountId}/scan][%d] scanAccountOK ", 200)
}

func (o *ScanAccountOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
