// Code generated by go-swagger; DO NOT EDIT.

package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewUpdateAccountSubscriptionParams creates a new UpdateAccountSubscriptionParams object
// with the default values initialized.
func NewUpdateAccountSubscriptionParams() *UpdateAccountSubscriptionParams {
	var ()
	return &UpdateAccountSubscriptionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateAccountSubscriptionParamsWithTimeout creates a new UpdateAccountSubscriptionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateAccountSubscriptionParamsWithTimeout(timeout time.Duration) *UpdateAccountSubscriptionParams {
	var ()
	return &UpdateAccountSubscriptionParams{

		timeout: timeout,
	}
}

// NewUpdateAccountSubscriptionParamsWithContext creates a new UpdateAccountSubscriptionParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateAccountSubscriptionParamsWithContext(ctx context.Context) *UpdateAccountSubscriptionParams {
	var ()
	return &UpdateAccountSubscriptionParams{

		Context: ctx,
	}
}

// NewUpdateAccountSubscriptionParamsWithHTTPClient creates a new UpdateAccountSubscriptionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateAccountSubscriptionParamsWithHTTPClient(client *http.Client) *UpdateAccountSubscriptionParams {
	var ()
	return &UpdateAccountSubscriptionParams{
		HTTPClient: client,
	}
}

/*UpdateAccountSubscriptionParams contains all the parameters to send to the API endpoint
for the update account subscription operation typically these are written to a http.Request
*/
type UpdateAccountSubscriptionParams struct {

	/*ID
	  Account ID

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update account subscription params
func (o *UpdateAccountSubscriptionParams) WithTimeout(timeout time.Duration) *UpdateAccountSubscriptionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update account subscription params
func (o *UpdateAccountSubscriptionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update account subscription params
func (o *UpdateAccountSubscriptionParams) WithContext(ctx context.Context) *UpdateAccountSubscriptionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update account subscription params
func (o *UpdateAccountSubscriptionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update account subscription params
func (o *UpdateAccountSubscriptionParams) WithHTTPClient(client *http.Client) *UpdateAccountSubscriptionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update account subscription params
func (o *UpdateAccountSubscriptionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the update account subscription params
func (o *UpdateAccountSubscriptionParams) WithID(id string) *UpdateAccountSubscriptionParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the update account subscription params
func (o *UpdateAccountSubscriptionParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateAccountSubscriptionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
