// Code generated by go-swagger; DO NOT EDIT.

package external_id

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/erikvanbrakel/terraform-provider-cloudconformity/go-cloudconformity/models"
)

// GetExternalIDReader is a Reader for the GetExternalID structure.
type GetExternalIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetExternalIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetExternalIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetExternalIDOK creates a GetExternalIDOK with default headers values
func NewGetExternalIDOK() *GetExternalIDOK {
	return &GetExternalIDOK{}
}

/*GetExternalIDOK handles this case with default header values.

OK
*/
type GetExternalIDOK struct {
	Payload *models.GetExternalIDOKBody
}

func (o *GetExternalIDOK) Error() string {
	return fmt.Sprintf("[GET /organisation/external-id][%d] getExternalIdOK  %+v", 200, o.Payload)
}

func (o *GetExternalIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetExternalIDOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
