// Code generated by go-swagger; DO NOT EDIT.

package rules

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetRuleSettingParams creates a new GetRuleSettingParams object
// with the default values initialized.
func NewGetRuleSettingParams() *GetRuleSettingParams {
	var ()
	return &GetRuleSettingParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetRuleSettingParamsWithTimeout creates a new GetRuleSettingParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetRuleSettingParamsWithTimeout(timeout time.Duration) *GetRuleSettingParams {
	var ()
	return &GetRuleSettingParams{

		timeout: timeout,
	}
}

// NewGetRuleSettingParamsWithContext creates a new GetRuleSettingParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetRuleSettingParamsWithContext(ctx context.Context) *GetRuleSettingParams {
	var ()
	return &GetRuleSettingParams{

		Context: ctx,
	}
}

// NewGetRuleSettingParamsWithHTTPClient creates a new GetRuleSettingParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetRuleSettingParamsWithHTTPClient(client *http.Client) *GetRuleSettingParams {
	var ()
	return &GetRuleSettingParams{
		HTTPClient: client,
	}
}

/*GetRuleSettingParams contains all the parameters to send to the API endpoint
for the get rule setting operation typically these are written to a http.Request
*/
type GetRuleSettingParams struct {

	/*AccountID
	  Account ID

	*/
	AccountID string
	/*RuleID
	  Rule ID

	*/
	RuleID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get rule setting params
func (o *GetRuleSettingParams) WithTimeout(timeout time.Duration) *GetRuleSettingParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get rule setting params
func (o *GetRuleSettingParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get rule setting params
func (o *GetRuleSettingParams) WithContext(ctx context.Context) *GetRuleSettingParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get rule setting params
func (o *GetRuleSettingParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get rule setting params
func (o *GetRuleSettingParams) WithHTTPClient(client *http.Client) *GetRuleSettingParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get rule setting params
func (o *GetRuleSettingParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAccountID adds the accountID to the get rule setting params
func (o *GetRuleSettingParams) WithAccountID(accountID string) *GetRuleSettingParams {
	o.SetAccountID(accountID)
	return o
}

// SetAccountID adds the accountId to the get rule setting params
func (o *GetRuleSettingParams) SetAccountID(accountID string) {
	o.AccountID = accountID
}

// WithRuleID adds the ruleID to the get rule setting params
func (o *GetRuleSettingParams) WithRuleID(ruleID string) *GetRuleSettingParams {
	o.SetRuleID(ruleID)
	return o
}

// SetRuleID adds the ruleId to the get rule setting params
func (o *GetRuleSettingParams) SetRuleID(ruleID string) {
	o.RuleID = ruleID
}

// WriteToRequest writes these params to a swagger request
func (o *GetRuleSettingParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param accountId
	if err := r.SetPathParam("accountId", o.AccountID); err != nil {
		return err
	}

	// path param ruleId
	if err := r.SetPathParam("ruleId", o.RuleID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
