// Code generated by go-swagger; DO NOT EDIT.

package rules

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// UpdateRuleSettingReader is a Reader for the UpdateRuleSetting structure.
type UpdateRuleSettingReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateRuleSettingReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewUpdateRuleSettingOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUpdateRuleSettingOK creates a UpdateRuleSettingOK with default headers values
func NewUpdateRuleSettingOK() *UpdateRuleSettingOK {
	return &UpdateRuleSettingOK{}
}

/*UpdateRuleSettingOK handles this case with default header values.

OK
*/
type UpdateRuleSettingOK struct {
}

func (o *UpdateRuleSettingOK) Error() string {
	return fmt.Sprintf("[PATCH /accounts/{accountId}/settings/rules/{ruleId}][%d] updateRuleSettingOK ", 200)
}

func (o *UpdateRuleSettingOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
