// Code generated by go-swagger; DO NOT EDIT.

package rules

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewUpdateRuleSettingParams creates a new UpdateRuleSettingParams object
// with the default values initialized.
func NewUpdateRuleSettingParams() *UpdateRuleSettingParams {
	var ()
	return &UpdateRuleSettingParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateRuleSettingParamsWithTimeout creates a new UpdateRuleSettingParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateRuleSettingParamsWithTimeout(timeout time.Duration) *UpdateRuleSettingParams {
	var ()
	return &UpdateRuleSettingParams{

		timeout: timeout,
	}
}

// NewUpdateRuleSettingParamsWithContext creates a new UpdateRuleSettingParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateRuleSettingParamsWithContext(ctx context.Context) *UpdateRuleSettingParams {
	var ()
	return &UpdateRuleSettingParams{

		Context: ctx,
	}
}

// NewUpdateRuleSettingParamsWithHTTPClient creates a new UpdateRuleSettingParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateRuleSettingParamsWithHTTPClient(client *http.Client) *UpdateRuleSettingParams {
	var ()
	return &UpdateRuleSettingParams{
		HTTPClient: client,
	}
}

/*UpdateRuleSettingParams contains all the parameters to send to the API endpoint
for the update rule setting operation typically these are written to a http.Request
*/
type UpdateRuleSettingParams struct {

	/*AccountID
	  Account ID

	*/
	AccountID string
	/*RuleID
	  Rule ID

	*/
	RuleID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update rule setting params
func (o *UpdateRuleSettingParams) WithTimeout(timeout time.Duration) *UpdateRuleSettingParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update rule setting params
func (o *UpdateRuleSettingParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update rule setting params
func (o *UpdateRuleSettingParams) WithContext(ctx context.Context) *UpdateRuleSettingParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update rule setting params
func (o *UpdateRuleSettingParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update rule setting params
func (o *UpdateRuleSettingParams) WithHTTPClient(client *http.Client) *UpdateRuleSettingParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update rule setting params
func (o *UpdateRuleSettingParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAccountID adds the accountID to the update rule setting params
func (o *UpdateRuleSettingParams) WithAccountID(accountID string) *UpdateRuleSettingParams {
	o.SetAccountID(accountID)
	return o
}

// SetAccountID adds the accountId to the update rule setting params
func (o *UpdateRuleSettingParams) SetAccountID(accountID string) {
	o.AccountID = accountID
}

// WithRuleID adds the ruleID to the update rule setting params
func (o *UpdateRuleSettingParams) WithRuleID(ruleID string) *UpdateRuleSettingParams {
	o.SetRuleID(ruleID)
	return o
}

// SetRuleID adds the ruleId to the update rule setting params
func (o *UpdateRuleSettingParams) SetRuleID(ruleID string) {
	o.RuleID = ruleID
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateRuleSettingParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param accountId
	if err := r.SetPathParam("accountId", o.AccountID); err != nil {
		return err
	}

	// path param ruleId
	if err := r.SetPathParam("ruleId", o.RuleID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
