// Code generated by go-swagger; DO NOT EDIT.

package rules

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// UpdateRuleSettingsReader is a Reader for the UpdateRuleSettings structure.
type UpdateRuleSettingsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateRuleSettingsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewUpdateRuleSettingsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUpdateRuleSettingsOK creates a UpdateRuleSettingsOK with default headers values
func NewUpdateRuleSettingsOK() *UpdateRuleSettingsOK {
	return &UpdateRuleSettingsOK{}
}

/*UpdateRuleSettingsOK handles this case with default header values.

OK
*/
type UpdateRuleSettingsOK struct {
}

func (o *UpdateRuleSettingsOK) Error() string {
	return fmt.Sprintf("[PATCH /accounts/{accountId}/settings/rules][%d] updateRuleSettingsOK ", 200)
}

func (o *UpdateRuleSettingsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
