// Code generated by go-swagger; DO NOT EDIT.

package rules

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewUpdateRuleSettingsParams creates a new UpdateRuleSettingsParams object
// with the default values initialized.
func NewUpdateRuleSettingsParams() *UpdateRuleSettingsParams {
	var ()
	return &UpdateRuleSettingsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateRuleSettingsParamsWithTimeout creates a new UpdateRuleSettingsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateRuleSettingsParamsWithTimeout(timeout time.Duration) *UpdateRuleSettingsParams {
	var ()
	return &UpdateRuleSettingsParams{

		timeout: timeout,
	}
}

// NewUpdateRuleSettingsParamsWithContext creates a new UpdateRuleSettingsParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateRuleSettingsParamsWithContext(ctx context.Context) *UpdateRuleSettingsParams {
	var ()
	return &UpdateRuleSettingsParams{

		Context: ctx,
	}
}

// NewUpdateRuleSettingsParamsWithHTTPClient creates a new UpdateRuleSettingsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateRuleSettingsParamsWithHTTPClient(client *http.Client) *UpdateRuleSettingsParams {
	var ()
	return &UpdateRuleSettingsParams{
		HTTPClient: client,
	}
}

/*UpdateRuleSettingsParams contains all the parameters to send to the API endpoint
for the update rule settings operation typically these are written to a http.Request
*/
type UpdateRuleSettingsParams struct {

	/*AccountID
	  Account ID

	*/
	AccountID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update rule settings params
func (o *UpdateRuleSettingsParams) WithTimeout(timeout time.Duration) *UpdateRuleSettingsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update rule settings params
func (o *UpdateRuleSettingsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update rule settings params
func (o *UpdateRuleSettingsParams) WithContext(ctx context.Context) *UpdateRuleSettingsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update rule settings params
func (o *UpdateRuleSettingsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update rule settings params
func (o *UpdateRuleSettingsParams) WithHTTPClient(client *http.Client) *UpdateRuleSettingsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update rule settings params
func (o *UpdateRuleSettingsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAccountID adds the accountID to the update rule settings params
func (o *UpdateRuleSettingsParams) WithAccountID(accountID string) *UpdateRuleSettingsParams {
	o.SetAccountID(accountID)
	return o
}

// SetAccountID adds the accountId to the update rule settings params
func (o *UpdateRuleSettingsParams) SetAccountID(accountID string) {
	o.AccountID = accountID
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateRuleSettingsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param accountId
	if err := r.SetPathParam("accountId", o.AccountID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
